version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/safewater
permissions:
  - object: /home/ubuntu/safewater
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
